### PR TITLE
Migrated to .net standard

### PR DESCRIPTION
**Pull request by alanwales**

### CODE REVIEW

**Comment by thomashunziker** [comment]
We are working on the proposed changes. We have to publish multiple versions within the same publication.

**Comment by tomkerkhove** [comment]
Any update on this @thomashunziker

**Comment by adamovic-cw** [comment]
@alanwales @tomkerkhove 
Hi,
First, sorry for not replying sooner. This took longer due to my lack of understanding what had to be changed.
I have updated SDK to support .NET Standard 2.0 and released a new version. 
Could you please verify if this works for you? 
In case there is any problem with the new version, it would be very helpful if you could suggest how to fix it.

**Comment by alanwales** [comment]
Thanks for the update, I can confirm it’s working great

**Pull request closed without merging**
